export const FEATURES = [
  {
    title: "Seasonal Roasts",
    description: "Discover our expertly curated selection of single-origin coffees, changing monthly to bring you the finest beans from around the world. Each roast is carefully selected at peak harvest and roasted to perfection to showcase its unique flavor profile. We provide tasting notes and brewing suggestions so you can recreate the experience at home, and our baristas are happy to recommend the ideal cup or pairing.",
  },
  {
    title: "Fresh Bakes",
    description: "Start your day with our freshly baked artisanal pastries and breads, prepared daily in our in-house bakery. From buttery croissants to wholesome sourdough, each item is crafted with premium ingredients and traditional techniques. We rotate flavors seasonally and offer a selection of gluten-free and vegan options, all baked in small batches to ensure peak freshness throughout the day.",
  },
  {
    title: "Community",
    description: "Join our vibrant coffee community where passion meets expertise. We host weekly tastings, brewing workshops, and local events that bring together coffee enthusiasts. Learn, share, and grow with fellow coffee lovers in a welcoming space. Events are designed for all experience levels with plenty of hands-on guidance, discussion, and opportunities to discover new brewing methods and origins.",
  },
  {
    title: "Sustainable Practices",
    description: "Our commitment to sustainability goes beyond recycling. We source ethically traded beans, use eco-friendly packaging, and partner with local farms for composting. Every cup you enjoy supports environmental responsibility. We also publish sourcing transparency and partner on community initiatives to reduce waste and support regenerative farming practices.",
  },
  {
    title: "Study Space",
    description: "Need a quiet spot to work or study? Our cafe offers free high-speed WiFi, plenty of power outlets, and comfortable seating. Enjoy a productive session with your favorite brew by your side. We maintain quiet hours, provide plug-and-play connectivity, and host occasional co-working meetups for students and freelancers.",
  },
];

export const SIGNATURE_DRINKS = [
  {
    id: "nitro",
    name: "Nitro Cold Brew",
    price: 5.25,
    gradient: "from-zinc-800 to-slate-400",
    description: "Smooth, pressurized cold brew infused with nitrogen for a creamy, stout-like texture and cascading effect",
    ingredients: "Cold Brew Coffee, Nitrogen Infusion",
    serving: "Served in a frozen glass with cascading nitrogen bubbles",
  },
  {
    id: "velvet",
    name: "Velvet Fog",
    price: 6.49,
    gradient: "from-red-900 to-rose-100",
    description: "Vanilla-infused cold brew topped with cloud-like whipped cream that slowly melts into the drink",
    ingredients: "Cold Brew, Vanilla Bean, Cream",
    serving: "Served in a smoky glass with gold rim",
  },
  {
    id: "midnight",
    name: "Midnight Serenade",
    price: 6.99,
    gradient: "from-purple-900 to-indigo-400",
    description: "Dark chocolate espresso infused with lavender and topped with edible silver dust",
    ingredients: "Espresso, Dark Chocolate, Lavender",
    serving: "Served in a matte black cup with a crescent cookie",
  },
  {
    id: "azure",
    name: "Azure Dream",
    price: 6.75,
    gradient: "from-sky-500 to-cyan-200",
    description: "Butterfly pea flower latte that changes color as you drink, topped with sea salt cream",
    ingredients: "Espresso, Butterfly Pea Flower, Sea Salt Cream",
    serving: "Served in a clear glass to showcase the color change",
  },
  {
    id: "honeycomb",
    name: "Honeycomb Whisper",
    price: 6.25,
    gradient: "from-amber-500 to-yellow-200",
    description: "Raw honey and cinnamon-infused cappuccino with a delicate honey art finish",
    ingredients: "Espresso, Raw Honey, Cinnamon",
    serving: "Served with a natural honeycomb piece",
  },
  {
    id: "alpine",
    name: "Alpine Mist",
    price: 5.99,
    gradient: "from-emerald-700 to-slate-100",
    description: "Pine-smoked espresso with maple cream and a hint of mountain herbs",
    ingredients: "Smoked Espresso, Maple Cream, Herbs",
    serving: "Served in a cedar-wrapped glass",
  },
  {
    id: "celestial",
    name: "Celestial Brew",
    price: 7.25,
    gradient: "from-indigo-900 to-purple-300",
    description: "Star anise and cardamom spiced coffee with gold-dusted milk foam",
    ingredients: "Coffee, Star Anise, Cardamom",
    serving: "Topped with constellation latte art",
  },
  {
    id: "caramel",
    name: "Caramel Dream",
    price: 4.99,
    gradient: "from-amber-700 to-cream-100",
    description: "A luxurious blend of espresso and velvety caramel, topped with cloud-like whipped cream and a golden caramel drizzle",
    ingredients: "Espresso, Caramel Syrup, Cream",
    serving: "Served in a crystal glass with a caramel-rimmed edge",
  },
];

export const PRODUCTS = [
  { id: "velvet-fog", name: "Velvet Fog", price: 6.49 },
  { id: "midnight-serenade", name: "Midnight Serenade", price: 6.99 },
  { id: "azure-dream", name: "Azure Dream", price: 6.75 },
  { id: "honeycomb-whisper", name: "Honeycomb Whisper", price: 6.25 },
  { id: "alpine-mist", name: "Alpine Mist", price: 5.99 },
  { id: "celestial-brew", name: "Celestial Brew", price: 7.25 },
  { id: "caramel", name: "Caramel Dream", price: 4.99 },
  { id: "dark", name: "Dark Roast", price: 3.99 },
  { id: "vanilla", name: "Vanilla Latte", price: 4.49 },
  { id: "mocha", name: "Mocha Blast", price: 5.49 },
  { id: "espresso", name: "Espresso Shot", price: 2.5 },
  { id: "americano", name: "Americano", price: 3.25 },
  { id: "cappuccino", name: "Cappuccino", price: 4.25 },
  { id: "flatwhite", name: "Flat White", price: 4.0 },
  { id: "latte", name: "Classic Latte", price: 4.0 },
  { id: "hazelnut", name: "Hazelnut Latte", price: 4.75 },
  { id: "matcha", name: "Matcha Latte", price: 5.0 },
  { id: "chai", name: "Chai Tea", price: 3.75 },
  { id: "iced-latte", name: "Iced Latte", price: 4.25 },
  { id: "cold-brew", name: "Cold Brew", price: 4.5 },
  { id: "nitro", name: "Nitro Cold Brew", price: 5.25 },
  { id: "affogato", name: "Affogato", price: 5.5 },
  { id: "frapuccino", name: "Mocha Frappé", price: 5.0 },
  { id: "cortado", name: "Cortado", price: 3.0 },
  { id: "macchiato", name: "Caramel Macchiato", price: 4.9 },
  { id: "hot-chocolate", name: "Hot Chocolate", price: 3.5 },
  { id: "tea", name: "Herbal Tea", price: 2.75 },
  { id: "smoothie", name: "Berry Smoothie", price: 5.75 },
];
